# Generated by Django 4.2.7 on 2026-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
