# Generated by Django 4.2.7 on 2026-03-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetableentry_lab_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timetable', 'timeslot')},
        ),
    ]
