# Generated by Django 4.2.7 on 2026-03-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_remove_classroom_timeslot_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultyavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.department'),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='facultyavailability',
            unique_together={('faculty', 'timeslot', 'department', 'semester')},
        ),
    ]
